stages:
  - doc
  - deploy

variables:
  PYTHON_VERSION: "registry.git.rwth-aachen.de/ebc/ebc_all/gitlab_ci/templates:python_3.11"
  PAGES_BRANCH: uesgraphs_gitcipipeline
  GIT_REPO: "RWTH-EBC/uesgraphs"


include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/doc/sphinxdoc.gitlab-ci.yml'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'pages/gh-pages.gitlab-ci.yml'  
