test_conda:
  image: continuumio/miniconda3
  stage: test

  before_script:
    #Set up environment
    - conda create -n python313 python=3.13 -y
    - source activate python313
    - python -V

    #Test tools
    - pip install coverage

    #Install uesgraphs
    - pip install --user --upgrade -e .

  script:
    - export MPLBACKEND=Agg #Backend to render matplot picture on the server without a screen
    - coverage run -m pytest --mpl tests/*.py --mpl-results-path=tests/result_images/ #switched from pytest --cov to coverage module
    - coverage report #Generates code coverage report after testing
   
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
  artifacts:
    when: on_failure
    paths:
      - tests/result_images/**/*.png #When pictures in tests/test_visuals.py do not match they will get stored here and can be downloaded in artifacts section

stages:
  - doc
  - deploy

variables:
  PYTHON_VERSION: "registry.git.rwth-aachen.de/ebc/ebc_all/gitlab_ci/templates:python_3.12"


include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/doc/sphinxdoc.gitlab-ci.yml'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'pages/gh-pages.gitlab-ci.yml'  
